dist: trusty
language: csharp
mono: none
dotnet: 2.1.403

env:
- NUGET_API=https://api.nuget.org/v3/index.json

before_script:
- "dotnet restore"

script:
- "dotnet build /p:CiBuildId=$TRAVIS_BUILD_NUMBER"
- "dotnet test CliToolkit.Tests --no-build"
- "./app-test.sh ~ --hidden --verbose"

deploy:
  skip_cleanup: true
  provider: script
  script: dotnet pack -c release /p:CiBuildNumber=$TRAVIS_BUILD_NUMBER && dotnet nuget push CliToolkit/bin/Release/CliToolkit.*.nupkg -k $NUGET_API_KEY -s $NUGET_API
  on:
    branch: master
